name: poker-llm
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python>=3.10,<3.12

  # PyTorch (core ML framework)
  - pytorch>=2.0.0
  # Note: torchvision and torchaudio removed - not needed for LLM inference
  
  # Essential dependencies for basic functionality
  - numpy>=1.21.0              # Required by PyTorch and eval7
  - tqdm>=4.64.0               # Progress bars (used in model loading)
  - pyyaml>=6.0                # Config file parsing
  
  # Pip-only packages
  - pip>=23.0.0
  - pip:
    # Core ML libraries (required for LLM)
    - transformers>=4.30.0
    - accelerate>=0.20.0
    - tokenizers>=0.13.0
    - safetensors>=0.3.0
    - huggingface-hub>=0.15.0
    - peft>=0.4.0
    
    # Poker evaluation library (required for hand analysis)
    - eval7>=0.1.0

# Optional dependencies (uncomment if needed):
# Development and analysis tools:
#   - jupyter                 # For notebooks
#   - ipython>=8.0.0         # Enhanced Python shell
#   - matplotlib>=3.6.0      # Plotting (only used in texas_solver)
#   - seaborn>=0.11.0        # Advanced plotting (unused)
#   - pandas>=1.5.0          # Data analysis (unused in main app)
#   - scipy>=1.9.0           # Scientific computing (unused in main app)
#   - scikit-learn>=1.2.0    # Machine learning (unused in main app)
#   - datasets>=2.10.0       # HuggingFace datasets (unused in main app)
#   - jsonlines>=3.0.0       # JSONL file handling (training only)
#   - requests>=2.28.0       # HTTP requests (might be used)

# GPU optimization (uncomment for NVIDIA GPU):
#   - bitsandbytes>=0.41.0   # 8-bit optimization
#   - flash-attn>=2.3.0      # Flash attention
#   - xformers>=0.0.22       # Memory efficient attention

# GUI dependencies:
# - tkinter is included with Python by default
# - tkinter-tooltip removed (not essential)